# Session Detail
session_title: تست نوشتن، چرا و چگونه؟ (قسمت اول)
session_provider: محمد محمودی
session_date: 2017-04-10 02:14:49 +0430
session_link: https://www.evand.com
session_provider_twitter_id: mm580486

# Site information
title: تهران جی اس | tehranjs
email: tehranjs@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  تِهران جِی اِس یه دورهمیه که از حدود یک سال پیش (اولین جلسه‌اش، ۱۱ اسفند ۹۴) تا حالا هر دو هفته یه بار توی
  شرکت رهنما برگزار شده و خواهد شد. توی این یک سال گذشته هم بیشتر درباره‌ی جاوااسکریپت صحبت کردیم. هر چند
  هدف اولیه برگزاری این نشست‌ها بیشتر تبادل تجربیات‌مون توی مدیریت، پیاده سازی و توسعه‌ی نرم افزار و مفاهیم
  پایه‌ی اون بوده که اگه ربطی هم به جاوااسکریپت داشتن چه بهتر.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://tehranjs.net" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: tehranjs
github_username:  tehranjs

# Build settings
include: ['_pages', '_events']
kramdown:
  input: GFM

gems:
  - jekyll-feed

# Sass settings
sass:
  sass_dir: assets/_scss
  style: :compressed

# Build settings
exclude:
  - Gemfile
  - Gemfile.lock
  - package.json
  - README.md
  - CNAME
  - node_modules

# Handling Readin
encoding: "utf-8"
